### PR TITLE
Did some rewording in the documentation

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
Did some rewording for detailed documentation.

### CODE REVIEW

**Comment by mikesch803** [comment]
LGTM

**Review by mikesch803 — APPROVED** [review]

**Review by VLeads — APPROVED** [review]
It's looking amazing. Keep up doing the good work !!

**Review by anik31 — APPROVED** [review]
LGTM

**Comment by shahbazibnafzal** [comment]
Thanks @mikesch803 , @anik31 and @VLeads  for reviews.

**Pull request merged**
