### PR TITLE
added responsive image component and fixed responsiveness of video card

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
1. Added responsive image component to BleedBlue component library
2. Fixed responsiveness of video card
3. Changed social media handle colors in the navbar

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM This is amazing Shahbaaz Keep on doing the good work.

**Review by Hamza-777 — APPROVED** [review]
Nice work shahbaz bhai keep it up.

**Review by ParthParolekar — APPROVED** [review]
It looks great. Nice work!

**Comment by shahbazibnafzal** [comment]
Thanks @Dev-AkshatGupta , @Hamza-777  and @ParthParolekar for your approval and the feedbacks, merging it to dev branch.

**Pull request merged**
