### PR TITLE
refactored the code and added hamburger for mobile menu

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
1. Removed unnecessary code.
2. Added hamburger for mobile view.
3. Corrected some CSS spacing for readability and consistency.

### CODE REVIEW

**Comment by anik31** [comment]
Hamburger was not working when I did these steps:
1. Decreased width of browser & played with the hamburger
2. When I increased the width again the header's height got reduced & navigations were unavailable

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM

**Comment by shahbazibnafzal** [comment]
Removed the hamburger.

**Review by nayyyhaa — APPROVED** [review]
Nice work. Clean code + UI LGTM 👍

**Comment by shahbazibnafzal** [comment]
Thanks @Dev-AkshatGupta, @anik31  and @nayyyhaa for the review. Merging it.

**Pull request merged**
