### PR TITLE
feat: Added card components to BleedBlue component library documentat…

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
1. Added horizonal card
2. Added horizontal card with badge
3. Added vertical cards with and without badges
4. Added card with text overlay
5. Added card with text only and dismiss
6. Added shadow to cards.

### CODE REVIEW

**Comment by Dev-AkshatGupta** [comment]
This is amazing man . This looks  awesome keep on doing good work . 💯

**Comment by Developers-codz** [comment]
UI is amazing !!!! Good Work.

**Review by Dev-AkshatGupta — APPROVED** [review]
This looks awesome

**Comment by anik31** [comment]
Looks very good

**Review by Developers-codz — APPROVED** [review]

**Comment by shahbazibnafzal** [comment]
Thanks @Dev-AkshatGupta , @Developers-codz  and @anik31  for the review and feedbacks. Merging the branch to dev.

**Pull request merged**
