### PR TITLE
Input Component

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
Added input component to the documentation website and removed unnecessary code.

### CODE REVIEW

**Review by ParthParolekar — APPROVED** [review]
Looks good to me! :+1:

**Review by Maianki — APPROVED** [review]
Looks good, you can merge it.

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM This is really amazing :)

**Comment by shahbazibnafzal** [comment]
Thanks @ParthParolekar , @Maianki  and @Maianki  for reviewing my PR. Merging it to dev.

**Pull request merged**
