### PR TITLE
feat: Added badge and button components to component library document…

### PR DESCRIPTION
**Pull request by shahbazibnafzal**
1. Added badge components
2. Added button components

### CODE REVIEW

**Comment by Dev-AkshatGupta** [comment]
Everything looks good to me except the colors you are using in the yellow alert boc just diffrentiate between color of those both buddy else everything works fine and seems good to me. :)

**Comment by partha8** [comment]
LGTM, and as @Dev-AkshatGupta said, you can improve the contrast.

**Comment by shahbazibnafzal** [comment]
thanks @Dev-AkshatGupta  and @partha8  for the suggestions, I have darken the text color on the yellow alert, kindly have a look and approve if it looks fine now.

**Review by partha8 — APPROVED** [review]
Great work!

**Comment by hsnice16** [comment]
Nice work on UI, Shahbaz. 👍

**Review by hsnice16 — APPROVED** [review]

**Comment by shahbazibnafzal** [comment]
Thanks @partha8  and @hsnice16 for approving the changes, merging it.

**Pull request merged**
